version: '3'
services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
  backend:
    build: .
    image: backend-go-notes-app
    ports:
      - '8000:8000'
